ai:
  default: EfficientSam (speed)
  mask:
    conf_threshold: 0.5
    device: cpu
    max_segments: 5
    min_area: 100
    postprocess: true
    preprocess: true
    simplify_tolerance: 1.0
  prompt:
    iou_threshold: 0.5
    score_threshold: 0.1
    text: ''
detection:
  advanced:
    max_size: 1533
    min_size: 500
    pre_nms_threshold: 0.5
    pre_nms_top_n: 1000
    score_threshold: 0.05
  conf_threshold: 0.6
  device: cuda
  filter_classes:
  - person
  max_detections: 10
  model_name: retinanet_resnet50_fpn
  nms_threshold: 0.45
  use_gpu_if_available: true
pose_estimation:
  advanced:
    keypoint_score_threshold: 0.2
    max_poses: 20
    min_keypoints: 5
    tracking_threshold: 0.5
    use_tracking: false
  conf_threshold: 0.6
  device: cuda
  keypoint_threshold: 0.5
  model_name: keypointrcnn_resnet50_fpn
  use_detection_results: true
yolov7:
  conf_threshold: 0.25
  device: cpu
  filter_classes: []
  iou_threshold: 0.45
  model_path: F:\GitHub\labelme\labelme\models\yolov7.pt
